language: go

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - master

sudo: false

before_install:
  - gotools=golang.org/x/tools

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure -v
  - go generate ./examples/test
  - go generate ./examples/hello

script:
  - go test -v ./test -service-start-delay 1000ms -http-client-timeout 60000ms
