// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/test.proto

/*
Package test is a generated protocol buffer package.

It is generated from these files:
	proto/test.proto

It has these top-level messages:
	SendRequest
	LargeRequest
	TestResponse
	EchoResponse
*/
package test

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Send request.
type SendRequest struct {
	// Value to send.
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *SendRequest) Reset()                    { *m = SendRequest{} }
func (m *SendRequest) String() string            { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()               {}
func (*SendRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SendRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Large request.
type LargeRequest struct {
	// Length of string to return in response.
	Length int64 `protobuf:"varint,1,opt,name=length" json:"length,omitempty"`
}

func (m *LargeRequest) Reset()                    { *m = LargeRequest{} }
func (m *LargeRequest) String() string            { return proto.CompactTextString(m) }
func (*LargeRequest) ProtoMessage()               {}
func (*LargeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LargeRequest) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

// Test response.
type TestResponse struct {
	// True if operation was a success.
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *TestResponse) Reset()                    { *m = TestResponse{} }
func (m *TestResponse) String() string            { return proto.CompactTextString(m) }
func (*TestResponse) ProtoMessage()               {}
func (*TestResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TestResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// Echo response.
type EchoResponse struct {
	// Echo from service.
	Echo string `protobuf:"bytes,1,opt,name=echo" json:"echo,omitempty"`
}

func (m *EchoResponse) Reset()                    { *m = EchoResponse{} }
func (m *EchoResponse) String() string            { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()               {}
func (*EchoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *EchoResponse) GetEcho() string {
	if m != nil {
		return m.Echo
	}
	return ""
}

func init() {
	proto.RegisterType((*SendRequest)(nil), "test.SendRequest")
	proto.RegisterType((*LargeRequest)(nil), "test.LargeRequest")
	proto.RegisterType((*TestResponse)(nil), "test.TestResponse")
	proto.RegisterType((*EchoResponse)(nil), "test.EchoResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TestService service

type TestServiceClient interface {
	// Send the value in the request.
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*TestResponse, error)
	// Echo the value in the request back in the response.
	Echo(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	// Large will send a large response message.
	Large(ctx context.Context, in *LargeRequest, opts ...grpc.CallOption) (*EchoResponse, error)
}

type testServiceClient struct {
	cc *grpc.ClientConn
}

func NewTestServiceClient(cc *grpc.ClientConn) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*TestResponse, error) {
	out := new(TestResponse)
	err := grpc.Invoke(ctx, "/test.TestService/Send", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) Echo(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := grpc.Invoke(ctx, "/test.TestService/Echo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) Large(ctx context.Context, in *LargeRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := grpc.Invoke(ctx, "/test.TestService/Large", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TestService service

type TestServiceServer interface {
	// Send the value in the request.
	Send(context.Context, *SendRequest) (*TestResponse, error)
	// Echo the value in the request back in the response.
	Echo(context.Context, *SendRequest) (*EchoResponse, error)
	// Large will send a large response message.
	Large(context.Context, *LargeRequest) (*EchoResponse, error)
}

func RegisterTestServiceServer(s *grpc.Server, srv TestServiceServer) {
	s.RegisterService(&_TestService_serviceDesc, srv)
}

func _TestService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test.TestService/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test.TestService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).Echo(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_Large_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LargeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).Large(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test.TestService/Large",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).Large(ctx, req.(*LargeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TestService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "test.TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _TestService_Send_Handler,
		},
		{
			MethodName: "Echo",
			Handler:    _TestService_Echo_Handler,
		},
		{
			MethodName: "Large",
			Handler:    _TestService_Large_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/test.proto",
}

func init() { proto.RegisterFile("proto/test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x51, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x89, 0xa6, 0xb5, 0x9d, 0xe4, 0xa1, 0x1d, 0x44, 0x4a, 0xf1, 0x41, 0x56, 0x90, 0x3e,
	0x35, 0xa8, 0x07, 0x28, 0x08, 0xbe, 0xf9, 0xb4, 0xf5, 0x02, 0xeb, 0x3a, 0x24, 0x81, 0xb0, 0x1b,
	0x33, 0x9b, 0x1c, 0xc0, 0x2b, 0x78, 0xb4, 0x5e, 0xc1, 0x83, 0xc8, 0x6e, 0x52, 0x89, 0x20, 0x7d,
	0x9b, 0x09, 0x5f, 0xbe, 0xf9, 0xf7, 0x87, 0x45, 0xdd, 0x58, 0x67, 0x33, 0x47, 0xec, 0xb6, 0x61,
	0xc4, 0xd8, 0xcf, 0xeb, 0xeb, 0xdc, 0xda, 0xbc, 0xa2, 0x4c, 0xd5, 0x65, 0xa6, 0x8c, 0xb1, 0x4e,
	0xb9, 0xd2, 0x1a, 0xee, 0x19, 0x71, 0x0b, 0xc9, 0x9e, 0xcc, 0xbb, 0xa4, 0x8f, 0x96, 0xd8, 0xe1,
	0x25, 0x4c, 0x3a, 0x55, 0xb5, 0xb4, 0x8a, 0x6e, 0xa2, 0xcd, 0x5c, 0xf6, 0x8b, 0xb8, 0x83, 0xf4,
	0x45, 0x35, 0x39, 0x1d, 0xa9, 0x2b, 0x98, 0x56, 0x64, 0x72, 0x57, 0x04, 0xec, 0x5c, 0x0e, 0x9b,
	0xd8, 0x40, 0xfa, 0x4a, 0xec, 0x24, 0x71, 0x6d, 0x0d, 0x13, 0xae, 0xe0, 0x82, 0x5b, 0xad, 0x89,
	0x39, 0x80, 0x33, 0x79, 0x5c, 0x85, 0x80, 0xf4, 0x59, 0x17, 0xf6, 0x97, 0x44, 0x88, 0x49, 0x17,
	0x76, 0x38, 0x1b, 0xe6, 0x87, 0x43, 0x04, 0x89, 0xd7, 0xed, 0xa9, 0xe9, 0x4a, 0x4d, 0xb8, 0x83,
	0xd8, 0x47, 0xc5, 0xe5, 0x36, 0xbc, 0x71, 0x14, 0x7b, 0x8d, 0xfd, 0xa7, 0xf1, 0x71, 0xb1, 0xf8,
	0x3c, 0x7c, 0x7f, 0x9d, 0x01, 0xce, 0xb2, 0xee, 0x3e, 0x63, 0xff, 0xe3, 0x0e, 0x62, 0x7f, 0xf4,
	0x84, 0x60, 0x9c, 0xe9, 0xaf, 0xc0, 0x27, 0xc2, 0x27, 0x98, 0x84, 0x1e, 0x70, 0xc0, 0xc7, 0xa5,
	0xfc, 0xab, 0x58, 0x06, 0x45, 0x82, 0x73, 0xaf, 0xa8, 0x3c, 0xfd, 0x36, 0x0d, 0xbd, 0x3f, 0xfe,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x45, 0xae, 0xc0, 0xe9, 0xaf, 0x01, 0x00, 0x00,
}
